const ProductActionTypes = {
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
    GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
    SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
}

export default ProductActionTypes;