const OrderActionTypes = {
    UPDATE_ORDER: 'UPDATE_ORDER',
    CREATE_ORDER: 'CREATE_ORDER',
    DELETE_ORDER: 'DELETE_ORDER',
    GET_ONE_ORDER: 'GET_ONE_ORDER',
    GET_ALL_ORDERS: 'GET_ALL_ORDERS',
    SET_ALL_ORDERS: 'SET_ALL_ORDERS',
    SET_CUSTOMER_ORDERS: 'SET_CUSTOMER_ORDERS',
}

export default OrderActionTypes;