export const FiltersActionTypes = {
    SET_SIDEBAR_FILTERS: 'SET_SIDEBAR_FILTERS',
    TOGGLE_SIDEBAR_DROPPED: 'TOGGLE_SIDEBAR_DROPPED',
    SET_SEARCHBAR_FILTERS: 'SET_SEARCHBAR_FILTERS',
    SET_SORTBAR_VALUE: 'SET_SORTBAR_VALUE',
    SET_VIEWBAR_VALUE: 'SET_VIEWBAR_VALUE',
    TOGGLE_VIEWBAR_GRID_LIST: 'TOGGLE_VIEWBAR_GRID_LIST',
    SET_V_PRODUCTS_FILTERS: 'SET_V_PRODUCTS_FILTERS',
    SET_VENDOR_FILTERS: 'SET_VENDOR_FILTERS',
    SET_DISPLAY_STATUS :'SET_DISPLAY_STATUS',
    SET_ORDER_FILTERS :'SET_ORDER_FILTERS',
}